name: CGO

on:
  workflow_dispatch:
    inputs:
      ver:
        required: true
        type: string

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        targets:
          - "!(*musl*|*windows-arm64*|*android*|*freebsd*|*windows7*)"
          - "linux-*-musl*"
          - "windows-arm64"
          - "android-*"
          - "freebsd-*"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.0"

      - name: Make release dir
        run: mkdir -p cgo-build-dist/

      - name: Build go program
        id: cgo-action
        uses: go-cross/cgo-actions@v1
        with:
          dir: "."
          targets: ${{ matrix.targets }}
          out-dir: cgo-build-dist/

      - name: Print Output
        id: output
        run: echo "${{ steps.cgo-action.outputs.files }}" && ls -alh cgo-build-dist/

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ strategy.job-index }}
          path: cgo-build-dist/

  release:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: cgo-build-dist/
          merge-multiple: true

      - name: List release files
        run: ls -l cgo-build-dist/

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.ver }}
          files: |
            cgo-build-dist/*
          name: Release ${{ github.event.inputs.ver }}
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
